import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import toast, { Toaster } from 'react-hot-toast';
import LandingNavbar from '@/components/LandingNavbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Fruad Report',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-gray-900 ${inter.className}`} >
      <LandingNavbar/>
        {children}
        <Toaster />
        </body>
    </html>
  )
}
